return {
  -- بلوجنات انميشن مجانية:
  
  -- Animation Tree [FREE]:
  https://create.roblox.com/store/asset/14023392079/Animation-Tree

  -- Moon Animator Object Exporter [FREE]:
  https://create.roblox.com/store/asset/14367322993/Moon-Animator-Object-Exporter

  -- Animation2Table [FREE]:
  https://create.roblox.com/store/asset/13461172333/Animation2Table

  -- Animation Spoofer (V2 Update!) [FREE]:
  https://create.roblox.com/store/asset/2537608092/Animation-Spoofer-V2-Update

  -- بلوجنات انميشن المدفوعة:
  
  -- Moon Animator (2) [29.99$]:
  https://create.roblox.com/store/asset/4725618216/Moon-Animator-2
}
